apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark-notebook
  labels:
    app: pyspark-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyspark-notebook
  template:
    metadata:
      labels:
        app: pyspark-notebook
    spec:
      containers:
      - name: pyspark-notebook
        image: jupyter/pyspark-notebook:latest
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
